version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_LIST_ID: ${BREVO_LIST_ID}
      PORT: 8080
    restart: always